version: "3.1"
services:
  
  nodejs:
    image: my_image:latest
    networks:
      - network_quickstart
    environment: 
      NODE_ENV: production
    ports:
      - 443:443
    restart: always
    extra_hosts:
      - "quickstart.hcl.com:127.0.0.1"
    working_dir: /home/QuickStartProjectPoC
    command: ["node", "index.js"]
    depends_on:
      - jenkins
  jenkins:
    image: mrshimpi17/jenkins
    networks:
      - network_quickstart
    ports:
      - 8081:8080
      - 50000:50000
networks:
 network_quickstart:
